# Generated by Django 5.0.9 on 2026-06-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
