# Generated by Django 5.0.9 on 2026-06-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudreport',
            name='reason',
            field=models.CharField(choices=[('fake_listing', 'Fake Listing'), ('misleading', 'Misleading Information'), ('scam', 'Scam'), ('wrong_price', 'Wrong Price'), ('not_available', 'Not Available'), ('harassment', 'Harassment'), ('abusive_behavior', 'Abusive Behavior'), ('non_payment', 'Non-payment'), ('property_damage', 'Property Damage'), ('unresponsive', 'Unresponsive'), ('other', 'Other')], max_length=30),
        ),
    ]
