# Generated by Django 5.0.9 on 2026-06-22 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('listings', '0002_listingadminview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ban_user', 'Banned user'), ('unban_user', 'Unbanned user'), ('restrict_user', 'Restricted user'), ('unrestrict_user', 'Unrestricted user'), ('reset_password', 'Sent password reset'), ('delete_user', 'Deleted user'), ('delete_listing', 'Deleted listing')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('target_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='listings.listing')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='common_admi_created_4bdb56_idx')],
            },
        ),
    ]
