# Generated by Django 5.0.9 on 2026-06-15 16:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room'), ('commercial', 'Commercial')], max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('price_annual', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('SLE', 'Sierra Leonean Leone'), ('USD', 'US Dollar')], default='SLE', max_length=5)),
                ('location_area', models.CharField(choices=[('aberdeen', 'Aberdeen'), ('lumley', 'Lumley'), ('goderich', 'Goderich'), ('hill_station', 'Hill Station'), ('wilberforce', 'Wilberforce'), ('murray_town', 'Murray Town'), ('brookfields', 'Brookfields'), ('kissy', 'Kissy'), ('wellington', 'Wellington'), ('calaba_town', 'Calaba Town'), ('other', 'Other')], max_length=30)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rented', 'Rented'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_notes', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='listings.listing')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_areas', models.JSONField(blank=True, default=list)),
                ('min_price', models.PositiveIntegerField(blank=True, null=True)),
                ('max_price', models.PositiveIntegerField(blank=True, null=True)),
                ('min_bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('property_types', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('search', 'Search'), ('save', 'Save'), ('inquiry', 'Inquiry'), ('click', 'Click')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='listings_li_status_63af6d_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['owner'], name='listings_li_owner_i_17ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location_area'], name='listings_li_locatio_ddd186_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_annual'], name='listings_li_price_a_241235_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='listing_search_vector_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('tenant', 'listing')},
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'event_type'], name='listings_us_user_id_b5e698_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['created_at'], name='listings_us_created_2df67b_idx'),
        ),
    ]
