# Generated by Django 5.0.9 on 2026-06-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_label', models.CharField(max_length=100)),
                ('original_key', models.CharField(blank=True, max_length=500)),
                ('tiles_prefix', models.CharField(blank=True, max_length=500)),
                ('thumbnail_key', models.CharField(blank=True, max_length=500)),
                ('preview_key', models.CharField(blank=True, max_length=500)),
                ('projection', models.CharField(blank=True, choices=[('equirectangular', 'Equirectangular'), ('cylindrical', 'Cylindrical')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='listings.listing')),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'indexes': [models.Index(fields=['listing', 'status'], name='panoramas_p_listing_0bf542_idx')],
            },
        ),
    ]
