# Generated by Django 5.0.9 on 2026-06-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoramas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panorama',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panorama',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
