# Generated by Django 5.0.9 on 2026-06-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('listing_decision', 'Listing Decision'), ('verification_result', 'Verification Result'), ('new_message', 'New Message'), ('report_update', 'Report Update'), ('panorama_ready', 'Panorama Ready'), ('moderation_warning', 'Moderation Warning')], max_length=40),
        ),
    ]
